export const restaurantList = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "591326",
        name: "The Chef Restaurant",
        uuid: "a1f22c86-2d79-4ada-88ce-77fd4f168bc2",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "hw2xrnjxo2u9viwjqlpa",
        cuisines: ["North Indian", "Chinese", "Fast Food", "Burgers", "Snacks"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 2.299999952316284,
        slugs: {
          restaurant: "the-chef-restaurant-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "Nanda Ki Chowki , Kolupani , Prem Nagar ,Dehradun - 248007, Vikasnagar, Dehradun, , Uttarakhand, 248007",
        locality: "Vishnupuri",
        parentId: 206631,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "591326",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 2.299999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.5",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "167612",
        name: "Tamilnadu Restaurant",
        uuid: "3d8f231b-4b6a-4877-bcc4-66fafdf5308b",
        city: "22",
        area: "Nanda Ki Chowki",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "seswrukq8zd4frig31te",
        cuisines: ["South Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 2.4000000953674316,
        slugs: {
          restaurant: "tamilnadu-restaurant-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "Subharti Hospital Road, Nanda Ki Chowki, Dehradun, Uttarakhand 248007, India",
        locality: "Prem Nagar",
        parentId: 200431,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹80 | Use code WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "167612",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 2.4000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "351726",
        name: "DA MEXICAN PIZZA",
        uuid: "46e0532a-586a-4256-90ec-5abe9bf45283",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "zaiqmbghvok9jlilbskh",
        cuisines: ["Italian", "Pizzas"],
        tags: [],
        costForTwo: 29900,
        costForTwoString: "₹299 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 4.300000190734863,
        slugs: {
          restaurant: "da-mexican-pizza-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "KH. NO-191, THAKURPUR ROAD PREM NAGAR, DEHRADUN, Dehradun Nagar Nigam, Dehradun, Uttarakhand, 248007",
        locality: "Thakurpur Road",
        parentId: 67423,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "60% off",
          shortDescriptionList: [
            {
              meta: "60% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "60% off up to ₹120 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "60% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "60% off up to ₹120 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=5669163~p=4~eid=00000185-d7f2-8db2-0fd7-61ad005a0453",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "351726",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 4.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.4",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "408570",
        name: "Dhaba Singh Darbar",
        uuid: "ea9950ff-adbb-46a2-bc75-f8a8e7df8e32",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "ckvrraxwm26x9uzpbfvd",
        cuisines: ["North Indian", "Chinese", "Snacks", "Sweets"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 2.700000047683716,
        slugs: {
          restaurant: "singh-darbar-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address: "Kheri gaon Prem Nagar, Opp Law College Dehradun, 248001",
        locality: "Kehri Gaon",
        parentId: 188420,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹80 | Use code WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "408570",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 2.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "460137",
        name: "Da Pepper Pizza",
        uuid: "7cb48ec1-9efe-4e6b-a6d6-7e3089b15168",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "ockiyuxbcg6vqszampp4",
        cuisines: ["Italian"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 4.300000190734863,
        slugs: {
          restaurant: "da-pepper-pizza-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address: "KH.,No.191,Thakurpur Road, Prem Nagar, Dehradun  248001",
        locality: "Thakurpur Road",
        parentId: 13393,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "60% off",
          shortDescriptionList: [
            {
              meta: "60% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "60% off up to ₹120 | Use code TRYNEW",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "60% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "60% off up to ₹120 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=5669245~p=7~eid=00000185-d7f2-8db2-0fd7-61ae005a070d",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "460137",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 4.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.5",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  // {
  //   cardType: "restaurant",
  //   layoutAlignmentType: "VERTICAL",
  //   data: {
  //     type: "restaurant",
  //     data: {
  //       type: "F",
  //       id: "387956",
  //       name: "Riders Readers Cafe",
  //       uuid: "f2028b0b-75f8-45b4-baa5-7546540b755c",
  //       city: "22",
  //       area: "Prem Nagar",
  //       totalRatingsString: "20+ ratings",
  //       cloudinaryImageId: "gsmaieuxytytcvel3f0u",
  //       cuisines: ["Indian", "North Indian", "Ice Cream", "Beverages"],
  //       tags: [],
  //       costForTwo: 25000,
  //       costForTwoString: "₹250 FOR TWO",
  //       deliveryTime: 35,
  //       minDeliveryTime: 35,
  //       maxDeliveryTime: 35,
  //       slaString: "35 MINS",
  //       lastMileTravel: 2.4000000953674316,
  //       slugs: {
  //         restaurant: "rider's-&-reader's-cafe-prem-nagar-prem-nagar",
  //         city: "dehradun",
  //       },
  //       cityState: "22",
  //       address: "Nanda Ki chowki, Prem Nagar, Dehradun",
  //       locality: "Prem Nagar",
  //       parentId: 253716,
  //       unserviceable: false,
  //       veg: false,
  //       select: false,
  //       favorite: false,
  //       tradeCampaignHeaders: [],
  //       aggregatedDiscountInfo: {
  //         header: "50% off",
  //         shortDescriptionList: [
  //           {
  //             meta: "50% off | Use WELCOME50",
  //             discountType: "Percentage",
  //             operationType: "RESTAURANT",
  //           },
  //         ],
  //         descriptionList: {
  //           meta: "50% off up to ₹80 | Use code WELCOME50",
  //           discountType: "Percentage",
  //           operationType: "RESTAURANT",
  //         },

  //         subHeader: "",
  //         headerType: 0,
  //         superFreedel: "",
  //       },
  //       aggregatedDiscountInfoV2: {
  //         header: "50% OFF",
  //         shortDescriptionList: [
  //           {
  //             meta: "Use WELCOME50",
  //             discountType: "Percentage",
  //             operationType: "RESTAURANT",
  //           },
  //         ],
  //         descriptionList: [
  //           {
  //             meta: "50% off up to ₹80 | Use code WELCOME50",
  //             discountType: "Percentage",
  //             operationType: "RESTAURANT",
  //           },
  //         ],
  //         subHeader: "",
  //         headerType: 0,
  //         superFreedel: "",
  //       },
  //       chain: [],
  //       feeDetails: {
  //         fees: [],
  //         totalFees: 0,
  //         message: "",
  //         title: "",
  //         amount: "",
  //         icon: "",
  //       },
  //       availability: {
  //         opened: true,
  //         nextOpenMessage: "",
  //         nextCloseMessage: "",
  //       },
  //       longDistanceEnabled: 0,
  //       rainMode: "NONE",
  //       thirdPartyAddress: false,
  //       thirdPartyVendor: "",
  //       adTrackingID: "",
  //       badges: {
  //         imageBased: [],
  //         textBased: [],
  //         textExtendedBadges: [],
  //       },
  //       lastMileTravelString: "2.4 kms",
  //       hasSurge: false,
  //       sla: {
  //         restaurantId: "387956",
  //         deliveryTime: 35,
  //         minDeliveryTime: 35,
  //         maxDeliveryTime: 35,
  //         lastMileTravel: 2.4000000953674316,
  //         lastMileDistance: 0,
  //         serviceability: "SERVICEABLE",
  //         rainMode: "NONE",
  //         longDistance: "NOT_LONG_DISTANCE",
  //         preferentialService: false,
  //         iconType: "EMPTY",
  //       },
  //       promoted: false,
  //       avgRating: "3.7",
  //       totalRatings: 20,
  //       new: false,
  //     },
  //     subtype: "basic",
  //   },
  //   parentWidget: false,
  // },

  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "615956",
        name: "Singh Darbar Sweets",
        uuid: "c04d0e5a-779f-4135-a78a-5dfb8ba32b6a",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "pr8vq3b9bzijp3ovn3yo",
        cuisines: ["Fast Food"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 2.700000047683716,
        slugs: {
          restaurant: "singh-darbar-sweets-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "Opp Uttranchal University Kheri Gaon  Prem nagar Dehradun, Arcadia Grant,  Dehradun Rural, Dehradun, Uttarakhand -  248001",
        locality: "Kheri Gaon",
        parentId: 367272,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹80 | Use code WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "615956",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 2.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.5",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "613857",
        name: "Take Away Kitchens",
        uuid: "be48348c-b953-4a56-808f-9e12f40b9a05",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "soeqlgruzkt7uhmell0j",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: "39 MINS",
        lastMileTravel: 2.4000000953674316,
        slugs: {
          restaurant: "take-away-kitchens-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "8XV4+G3J, Nanda Ki Chowki, Dehradun, Uttarakhand 248007, India",
        locality: "Nanda Ki Chowki",
        parentId: 366140,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹80 | Use code WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "613857",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 2.4000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "106094",
        name: "Taste Buds",
        uuid: "660da29c-90bb-45ae-a3ea-6fcd22c36bd3",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "heyqtzswgwbuhtvntlru",
        cuisines: ["Chinese", "Italian"],
        tags: [],
        costForTwo: 27500,
        costForTwoString: "₹275 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 4,
        slugs: {
          restaurant: "tastebuds-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address: "wing no.3, mdda park road opposite, elloras bakery premnagar",
        locality: "Prem Nagar",
        parentId: 3184,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: {
            meta: "50% off | Use WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "106094",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 4,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "307393",
        name: "TIRU BIRYANI",
        uuid: "9b414d8c-b7f0-4c71-aec8-90e9d8ad9584",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "vuay9ckdltzwpd42ihyu",
        cuisines: ["Biryani", "South Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant: "tiru-biryani-ballupur-ballupur",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "43E Kheri gaon premnagar, Kheri Mansingh, Dehradun Rural, Dehradun, Uttarakhand - 248007 Area: Premnagar City: Dehradun",
        locality: "Premnagar",
        parentId: 14741,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "Flat ₹125 off",
          shortDescriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹249",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "Flat ₹125 off on orders above ₹249 | Use code FLAT125",
            discountType: "Flat",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹125 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLAT125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹249 | Use code FLAT125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "307393",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.5",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "446041",
        name: "LOVE BIRDS FAMILY RESTAURANT",
        uuid: "6ae47bb7-94a2-4a2c-b3f2-c2cb44c2b502",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "vkxqwjzfmq8po2k4vtnu",
        cuisines: ["North Indian", "Chinese"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "love-birds-family-restaurant-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "SUDHOWALA, Sudhauwala, Vikasnagar,  Dehradun, Uttarakhand - 248007",
        locality: "Prem Nagar",
        parentId: 268678,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹80 | Use code WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "446041",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "667740",
        name: "Mirchi Cafe",
        uuid: "d91e869b-0beb-49a3-8039-671ae2f62d4a",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "f85b6c5866176dc50690636803b73270",
        cuisines: ["Biryani", "Kebabs", "Snacks"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "mirchi-cafe-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "4, Chakrata Rd, Tyagi Market, Shahpur, Prem Nagar, Dehradun, Uttarakhand 248007, India",
        locality: "Chakrata Rd",
        parentId: 136755,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹80 | Use code WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "667740",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: true,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "587055",
        name: "Annpurna Grand",
        uuid: "9cb406f6-c1fd-4300-89fa-154460e9d21b",
        city: "22",
        area: "Prem Nagar",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "vnc3opea2rkhipopphor",
        cuisines: ["North Indian", "Chinese", "Desserts"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        slaString: "42 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "annpurna-grand-prem-nagar-prem-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "Chakrata Road Khasra No 754 Shoudhawala, Vikasnagar, Dehradun, Uttarakhand",
        locality: "Prem Nagar",
        parentId: 351244,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹80 | Use code WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "587055",
          deliveryTime: 42,
          minDeliveryTime: 42,
          maxDeliveryTime: 42,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  // {
  //   cardType: "restaurant",
  //   layoutAlignmentType: "VERTICAL",
  //   data: {
  //     type: "restaurant",
  //     data: {
  //       type: "F",
  //       id: "605850",
  //       name: "Eat N Treat",
  //       uuid: "83ce037f-6fc1-4518-a5ed-ec40a80f9f72",
  //       city: "22",
  //       area: "Prem Nagar",
  //       totalRatingsString: "20+ ratings",
  //       cloudinaryImageId: "tb5alx7apq0aiwbbmiu4",
  //       cuisines: ["Chinese", "Pizzas", "Beverages"],
  //       tags: [],
  //       costForTwo: 25000,
  //       costForTwoString: "₹250 FOR TWO",
  //       deliveryTime: 43,
  //       minDeliveryTime: 43,
  //       maxDeliveryTime: 43,
  //       slaString: "43 MINS",
  //       lastMileTravel: 3.799999952316284,
  //       slugs: {
  //         restaurant: "eat-n-treat-prem-nagar-prem-nagar-2",
  //         city: "dehradun",
  //       },
  //       cityState: "22",
  //       address:
  //         "Khasra No 384 Suddhowala Chowk, Sudhauwala, Vikasnagar, Dehradun, Uttarakhand",
  //       locality: "Vikasnagar",
  //       parentId: 76042,
  //       unserviceable: false,
  //       veg: false,
  //       select: false,
  //       favorite: false,
  //       tradeCampaignHeaders: [],
  //       aggregatedDiscountInfo: {
  //         header: "Flat ₹125 off",
  //         shortDescriptionList: [
  //           {
  //             meta: "Flat ₹125 off on orders above ₹299",
  //             discountType: "Flat",
  //             operationType: "RESTAURANT",
  //           },
  //         ],
  //         descriptionList: {
  //           meta: "Flat ₹125 off on orders above ₹299 | Use code FLAT125",
  //           discountType: "Flat",
  //           operationType: "RESTAURANT",
  //         },

  //         subHeader: "",
  //         headerType: 0,
  //         superFreedel: "",
  //       },
  //       aggregatedDiscountInfoV2: {
  //         header: "₹125 OFF",
  //         shortDescriptionList: [
  //           {
  //             meta: "Use FLAT125",
  //             discountType: "Flat",
  //             operationType: "RESTAURANT",
  //           },
  //         ],
  //         descriptionList: [
  //           {
  //             meta: "Flat ₹125 off on orders above ₹299 | Use code FLAT125",
  //             discountType: "Flat",
  //             operationType: "RESTAURANT",
  //           },
  //         ],
  //         subHeader: "",
  //         headerType: 0,
  //         superFreedel: "",
  //       },
  //       chain: [],
  //       feeDetails: {
  //         fees: [],
  //         totalFees: 0,
  //         message: "",
  //         title: "",
  //         amount: "",
  //         icon: "",
  //       },
  //       availability: {
  //         opened: true,
  //         nextOpenMessage: "",
  //         nextCloseMessage: "",
  //       },
  //       longDistanceEnabled: 0,
  //       rainMode: "NONE",
  //       thirdPartyAddress: false,
  //       thirdPartyVendor: "",
  //       adTrackingID: "",
  //       badges: {
  //         imageBased: [],
  //         textBased: [],
  //         textExtendedBadges: [],
  //       },
  //       lastMileTravelString: "3.7 kms",
  //       hasSurge: false,
  //       sla: {
  //         restaurantId: "605850",
  //         deliveryTime: 43,
  //         minDeliveryTime: 43,
  //         maxDeliveryTime: 43,
  //         lastMileTravel: 3.799999952316284,
  //         lastMileDistance: 0,
  //         serviceability: "SERVICEABLE",
  //         rainMode: "NONE",
  //         longDistance: "NOT_LONG_DISTANCE",
  //         preferentialService: false,
  //         iconType: "EMPTY",
  //       },
  //       promoted: false,
  //       avgRating: "3.0",
  //       totalRatings: 20,
  //       new: false,
  //     },
  //     subtype: "basic",
  //   },
  //   parentWidget: false,
  // },
  {
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "552518",
        name: "Udupi Cafe North India",
        uuid: "ea26780d-8b18-4f25-9207-54855d9fb594",
        city: "22",
        area: "Suddhowala",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "jcz8tpqaooxmgd1z4pvq",
        cuisines: ["South Indian", "Snacks", "Fast Food", "Beverages"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        slaString: "40 MINS",
        lastMileTravel: 5,
        slugs: {
          restaurant: "udupi-cafe-north-india-patel-nagar-patel-nagar",
          city: "dehradun",
        },
        cityState: "22",
        address:
          "Village- Jhajra, Post- Sudhowala, Dehradun, Uttarakhand-248001",
        locality: "Patel Nagar",
        parentId: 331826,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: {
            meta: "50% off up to ₹80 | Use code WELCOME50",
            discountType: "Percentage",
            operationType: "RESTAURANT",
          },

          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹80 | Use code WELCOME50",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=5669232~p=1~eid=00000185-d7f2-8db2-0fd7-61ac005a0119",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "552518",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          lastMileTravel: 5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

export const MENU_URL =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=30.3164945&lng=78.03219179999999&restaurantId=";
export const IMG_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";
export const RESTAURANT_LIST =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=23.369726076519406&lng=85.33414583862306&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING";
